set echo off
set array 2500
set verify off
set termout on
-- set heading off
set headsep off
set pagesize 50000
set colsep ","
set pages 50000
set feedback off
set trimspool on
set null "-"
set newpage 1
set linesize 5000
spool /mnt/Post_Ready/zProd_Server/imageServer7/tmp/limbo/spoolexiftoolCsvMetaData.csv
-- spool /Users/johnb/Dropbox/exifFixed.csv

SELECT /* PrdExtra_CSV_UPDATES4776e2 */  /* CSV_UPDATES129650 */  DISTINCT
  POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE        AS "SourceFile",
  POMGR_SNP.PRODUCT_SNAPSHOT.BRAND             AS "XMP:Artist",
  ATG_SNP.EVENT_GROUP.NAME                     AS "XMP:Album",
  POMGR_SNP.PRODUCT_SNAPSHOT.START_DATE        AS "IPTC:SpecialInstructions",
  POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL4_NAME       AS "XMP:Genre",
  POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_STATUS AS "IPTC:CopyrightNotice",
  MAX(DISTINCT ATG_SNP.EVENT_GROUP.ID)         AS "IPTC:Credit",
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS     AS "IPTC:Source",
  POMGR_SNP.PRODUCT_SNAPSHOT.BRAND             AS "Keywords"
FROM
  POMGR_SNP.PRODUCT_SNAPSHOT
LEFT JOIN ATG_SNP.EVENT_PRODUCT_COLOR Event_ID_StyleNumber
ON
  POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE = Event_ID_StyleNumber.PRODUCT_COLOR_ID
LEFT JOIN ATG_SNP.EVENT_GROUP
ON
  ATG_SNP.EVENT_GROUP.ID = Event_ID_StyleNumber.EVENT_ID
WHERE
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS = 'Scanned In at Bluefly'
OR
  POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_STATUS  = 'Production Incomplete'
  AND POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS   != 'Pending Sample'
  AND POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS != 'Sample Sent to Bluefly'
  AND POMGR_SNP.PRODUCT_SNAPSHOT.INACTIVE_REASON IS NULL
GROUP BY
  POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE,
  POMGR_SNP.PRODUCT_SNAPSHOT.BRAND,
  ATG_SNP.EVENT_GROUP.NAME,
  POMGR_SNP.PRODUCT_SNAPSHOT.START_DATE,
  POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL4_NAME,
  POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_STATUS,
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS
HAVING
  SUM(DISTINCT POMGR_SNP.PRODUCT_SNAPSHOT.AVAILABLE_ON_HAND) > 0
ORDER BY
  POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE DESC Nulls Last;
spool off
exit;
