SELECT DISTINCT
  POMGR_SNP.SKU.SKU_CODE                                     AS sku,
  POMGR_SNP.SKU.PRODUCT_COLOR_ID                             AS colorstyle,
  POMGR_SNP.LK_SHIPMENT_STATUS.NAME                          AS "receiving_status",
  to_date(POMGR_SNP.SHP_HDR.DOCK_DATE, 'YYYY-MM-DD')         AS "dock_date",
  to_date(POMGR_SNP.SHP_HDR.IN_RECEIVING_DATE, 'YYYY-MM-DD') AS
  "in_receiving_date",
  to_date(POMGR_SNP.SHP_HDR.RECEIVE_DATE, 'YYYY-MM-DD')           AS "receive_date",
  POMGR_SNP.INVENTORY.TOTAL_WH_RCVD_QTY                           AS "quantity_received",
  POMGR_SNP.INVENTORY.AVAL_ON_HAND                                AS "quantity_onhand",
  to_date(POMGR_SNP.SHP_HDR.SENT_TO_WAREHOUSE_DATE, 'YYYY-MM-DD') AS
  "vendor_ship_date",
  POMGR_SNP.SHP_HDR.SHIPMENT_NUMBER              AS "shipment_number",
  POMGR_SNP.SHP_HDR.RECEIVING_STATUS_ID          AS "receiving_status_id",
  POMGR_SNP.VENDOR_SIZE_VALUE.NAME               AS "vendor_size",
  POMGR_SNP.VENDOR_SIZE_VALUE.BFLY_SIZE_VALUE_ID AS "bluefly_size",
  POMGR_SNP.VENDOR_SIZE_VALUE.SAMPLE_SIZE        AS "sample_flag",
  POMGR_SNP.SKU.VENDOR_SIZE_VALUE_ID             AS "vendor_size_id",
  POMGR_SNP.PO_LINE.REPLENISH_FLAG               AS "replenish_flag",
  POMGR_SNP.USERS.USERNAME                       AS "username"
FROM
  POMGR_SNP.PO_HDR
LEFT JOIN POMGR_SNP.SHP_HDR
ON
  POMGR_SNP.PO_HDR.ID = POMGR_SNP.SHP_HDR.PO_HDR_ID
INNER JOIN POMGR_SNP.USERS
ON
  POMGR_SNP.USERS.ID = POMGR_SNP.PO_HDR.USER_ID
LEFT JOIN POMGR_SNP.PO_LINE
ON
  POMGR_SNP.PO_HDR.ID = POMGR_SNP.PO_LINE.PO_HDR_ID
LEFT JOIN POMGR_SNP.PO_SKU
ON
  POMGR_SNP.PO_LINE.ID = POMGR_SNP.PO_SKU.PO_LINE_ID
RIGHT JOIN POMGR_SNP.SKU
ON
  POMGR_SNP.PO_SKU.SKU_ID = POMGR_SNP.SKU.ID
INNER JOIN POMGR_SNP.VENDOR_SIZE_VALUE
ON
  POMGR_SNP.SKU.VENDOR_SIZE_VALUE_ID = POMGR_SNP.VENDOR_SIZE_VALUE.ID
INNER JOIN POMGR_SNP.INVENTORY
ON
  POMGR_SNP.SKU.ID = POMGR_SNP.INVENTORY.SKU_ID
LEFT JOIN POMGR_SNP.LK_SHIPMENT_STATUS
ON
  POMGR_SNP.SHP_HDR.RECEIVING_STATUS_ID = POMGR_SNP.LK_SHIPMENT_STATUS.ID
WHERE
  POMGR_SNP.SHP_HDR.DOCK_DATE is not null  
ORDER BY
  POMGR_SNP.SKU.PRODUCT_COLOR_ID DESC,
  POMGR_SNP.SKU.SKU_CODE DESC