-- Unable to render TABLE DDL for object ATG_SNP.EVENT_PRODUCT_COLOR with
-- DBMS_METADATA attempting internal generator.
CREATE
  TABLE ATG_SNP.EVENT_PRODUCT_COLOR
  (
    EVENT_ID         NUMBER NOT NULL ,
    PRODUCT_COLOR_ID NUMBER NOT NULL ,
    SORT_ORDER       NUMBER(*, 0) NOT NULL ,
    CONSTRAINT PK_EVENT_PRODUCT_COLOR PRIMARY KEY ( EVENT_ID , PRODUCT_COLOR_ID
    ) ENABLE
  )
  NOLOGGING TABLESPACE "ATG_SNP_DATA" PCTFREE 10 INITRANS 1 STORAGE
  (
    INITIAL 81920 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT
  )
