CREATE TABLE POMGR_SNP.PRODUCT_SNAPSHOT 
(
  MASTER_STYLE NUMBER NOT NULL 
, COLORSTYLE NUMBER(38, 0) NOT NULL 
, SKU VARCHAR2(20 BYTE) 
, PO_HDR NUMBER(38, 0) 
, ACTIVE CHAR(1 BYTE) 
, MAIN_IMAGE CHAR(1 BYTE) 
, ZOOM_IMAGE CHAR(1 BYTE) 
, ALT_1 CHAR(1 BYTE) 
, ALT_2 CHAR(1 BYTE) 
, ALT_3 CHAR(1 BYTE) 
, ALT_4 CHAR(1 BYTE) 
, ALT_5 CHAR(1 BYTE) 
, IMAGE_SWATCH VARCHAR2(4000 BYTE) 
, COPY_READY DATE 
, IMAGE_READY DATE 
, PRODUCTION_STATUS VARCHAR2(255 BYTE) 
, PRODUCTION_COMPLETE_DT DATE 
, MERCHANT_STATUS VARCHAR2(255 BYTE) 
, MERCHANT_COMPLETE_DT DATE 
, START_DATE DATE 
, END_DATE DATE 
, ORIGINAL_START_DATE DATE 
, INACTIVE_DEPARTMENT NUMBER(*, 0) 
, INACTIVE_REASON VARCHAR2(4000 BYTE) 
, DNA_FLAG CHAR(1 BYTE) 
, SEASON VARCHAR2(255 BYTE) 
, YEAR NUMBER(4, 0) 
, ORIGINAL_SEASON VARCHAR2(255 BYTE) 
, ORIGINAL_YEAR NUMBER(4, 0) 
, BRAND VARCHAR2(255 BYTE) 
, BRAND_TYPE VARCHAR2(255 BYTE) 
, VENDOR_SIZE_CHART VARCHAR2(255 BYTE) 
, BLUEFLY_SIZE_CHART VARCHAR2(255 BYTE) 
, VENDOR_SIZE_VALUE VARCHAR2(255 BYTE) 
, BLUEFLY_SIZE_VALUE VARCHAR2(255 BYTE) 
, COUNTRY_OF_ORIGIN VARCHAR2(2 BYTE) 
, FUR_ORIGIN VARCHAR2(255 BYTE) 
, MATERIAL VARCHAR2(300 BYTE) 
, CARE_INSTRUCTIONS VARCHAR2(40 BYTE) 
, PRODUCT_SPECIAL_INFO VARCHAR2(255 BYTE) 
, PRODUCT_SIZE_CHART VARCHAR2(255 BYTE) 
, GIFT_WRAP CHAR(1 BYTE) 
, PRODUCT_SHORT_NAME VARCHAR2(255 BYTE) 
, PRODUCT_LONG_DESCRIPTION VARCHAR2(4000 BYTE) 
, COLOR_GROUP VARCHAR2(255 BYTE) 
, COLOR_DESCRIPTION VARCHAR2(255 BYTE) 
, VENDOR_STYLE_NO VARCHAR2(255 BYTE) 
, BULLET_1 VARCHAR2(1024 BYTE) 
, BULLET_2 VARCHAR2(1024 BYTE) 
, BULLET_3 VARCHAR2(1024 BYTE) 
, BULLET_4 VARCHAR2(1024 BYTE) 
, BULLET_5 VARCHAR2(1024 BYTE) 
, BULLET_6 VARCHAR2(1024 BYTE) 
, BULLET_7 VARCHAR2(1024 BYTE) 
, BULLET_8 VARCHAR2(1024 BYTE) 
, BULLET_9 VARCHAR2(1024 BYTE) 
, WEIGHT NUMBER(38, 2) 
, PERFECT_MATCH NUMBER(38, 0) 
, KEYWORD_DESIGN VARCHAR2(50 BYTE) 
, KEYWORD_MATERIAL VARCHAR2(50 BYTE) 
, KEYWORD_STYLE_1 VARCHAR2(50 BYTE) 
, KEYWORD_STYLE_2 VARCHAR2(50 BYTE) 
, KEYWORD_STYLE_3 VARCHAR2(50 BYTE) 
, KEYWORD_FIT VARCHAR2(50 BYTE) 
, KEYWORD_OCCASION VARCHAR2(50 BYTE) 
, KEYWORD_TREND VARCHAR2(50 BYTE) 
, CORETMETRICS_CATEGORY VARCHAR2(32 BYTE) 
, BML_CODE VARCHAR2(42 BYTE) 
, TAX_CODE VARCHAR2(85 BYTE) 
, FIRST_COST NUMBER(38, 2) 
, WHOLESALE NUMBER(38, 2) 
, MSRP NUMBER(38, 2) 
, BLUEFLY NUMBER(38, 2) 
, PRICE NUMBER(38, 2) 
, REDUCED_PRICE NUMBER(38, 2) 
, CLEARENCE_PRICE NUMBER(38, 2) 
, SALE_PRICE NUMBER(38, 2) 
, SELLING_PRICE NUMBER 
, TOTAL_RECVD NUMBER 
, TOTAL_ON_HAND NUMBER 
, AVAILABLE_ON_HAND NUMBER 
, LEVEL1_NAME VARCHAR2(4000 BYTE) 
, LEVEL2_NAME VARCHAR2(4000 BYTE) 
, LEVEL3_NAME VARCHAR2(4000 BYTE) 
, LEVEL4_NAME VARCHAR2(4000 BYTE) 
, LEVEL5_NAME VARCHAR2(4000 BYTE) 
, LEVEL6_NAME VARCHAR2(4000 BYTE) 
, LEVEL7_NAME VARCHAR2(4000 BYTE) 
, SAMPLE_STATUS VARCHAR2(35 BYTE) 
, SAMPLE_STATUS_DATE DATE 
, RETURN_POLICY VARCHAR2(85 BYTE) 
, SAMPLE_IMAGE CHAR(1 BYTE) 
, PHOTOGRAPHED_DATE DATE 
) 
LOGGING 
TABLESPACE "POMGR_SNP_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 81920 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)ALTER TABLE POMGR_SNP.PRODUCT_SNAPSHOT
ADD CONSTRAINT SYS_C00382889 CHECK 
(SKU IS NOT NULL)
DISABLE
ALTER TABLE POMGR_SNP.PRODUCT_SNAPSHOT
ADD CONSTRAINT SYS_C00382890 CHECK 
(ACTIVE IS NOT NULL)
DISABLE
ALTER TABLE POMGR_SNP.PRODUCT_SNAPSHOT
ADD CONSTRAINT SYS_C00382891 CHECK 
(COLOR_GROUP IS NOT NULL)
DISABLE
ALTER TABLE POMGR_SNP.PRODUCT_SNAPSHOT
ADD CONSTRAINT SYS_C00382892 CHECK 
(FIRST_COST IS NOT NULL)
DISABLE
ALTER TABLE POMGR_SNP.PRODUCT_SNAPSHOT
ADD CONSTRAINT SYS_C00382893 CHECK 
(BLUEFLY IS NOT NULL)
DISABLE
ALTER TABLE POMGR_SNP.PRODUCT_SNAPSHOT
ADD CONSTRAINT SYS_C00382894 CHECK 
(PRICE IS NOT NULL)
DISABLE