set echo off
set verify off
set termout on
set array 3000                      
-- set heading on
set headsep off
set pagesize 50000
set colsep ","
set pages 50000
set feedback off
--set tab on
set trimspool on
-- recsep 
--set trimout on
set null "NULL"
set newpage none
set linesize 5000
spool /mnt/Post_Ready/zProd_Server/imageServer7/tmp/limbo/spoolDWMerchantTags.csv

SELECT DISTINCT
  POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE             AS "SourceFile",
  POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_STATUS      AS "IPTC:CopyrightNotice",
  POMGR_SNP.PRODUCT_SNAPSHOT.PO_HDR                 AS "IPTC:PONumber",
  POMGR_SNP.USERS.USERNAME                          AS "IPTC:MerchantName",
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS          AS "IPTC:Source",
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS_DATE     AS "IPTC:SampleStatusDate",
  SUM(POMGR_SNP.PRODUCT_SNAPSHOT.AVAILABLE_ON_HAND) AS "IPTC:SampleInventory"
FROM
  POMGR_SNP.PRODUCT_SNAPSHOT
LEFT JOIN ATG_SNP.EVENT_PRODUCT_COLOR Event_ID_StyleNumber
ON
  POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE = Event_ID_StyleNumber.PRODUCT_COLOR_ID
LEFT JOIN ATG_SNP.EVENT_GROUP
ON
  ATG_SNP.EVENT_GROUP.ID = Event_ID_StyleNumber.EVENT_ID
INNER JOIN POMGR_SNP.PO_HDR
ON
  POMGR_SNP.PRODUCT_SNAPSHOT.PO_HDR = POMGR_SNP.PO_HDR.ID
INNER JOIN POMGR_SNP.USERS
ON
  POMGR_SNP.USERS.ID = POMGR_SNP.PO_HDR.USER_ID
WHERE
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS_DATE >= t_sys_log ((date) - 30)
AND POMGR_SNP.PRODUCT_SNAPSHOT.INACTIVE_REASON  IS NULL
AND POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS = 'Scanned In at Bluefly'
OR  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS = 'Sample Sent to Bluefly'
OR  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS = 'Scanned Out to Buyers'
GROUP BY
  POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE,
  POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_STATUS,
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS,
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS_DATE,
  POMGR_SNP.PRODUCT_SNAPSHOT.PO_HDR,
  POMGR_SNP.USERS.USERNAME
HAVING
  SUM(POMGR_SNP.PRODUCT_SNAPSHOT.AVAILABLE_ON_HAND)            >= 0
ORDER BY
  POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE DESC Nulls Last;
spool off
exit;
t_sys_log (date) VALUES ( date '2011-12-31');

