SELECT
  POMGR_SNP."SAMPLE".ID AS sample_id,
  POMGR_SNP."SAMPLE".PRODUCT_COLOR_ID,
  POMGR_SNP.SKU.SKU_CODE                                     AS sku,
  POMGR_SNP.TRACKING_NUMBER.REF_NUMBER                       AS UPS_TrackingID,
  to_date(POMGR_SNP.TRACKING_NUMBER.CREATE_DT, 'YYYY-MM-DD') AS Tracking_Date,
  MAX(DISTINCT POMGR_SNP.LK_SAMPLE_STATUS.NAME)              AS sample_status,
  POMGR_SNP.USERS.USERNAME
FROM
  POMGR_SNP."SAMPLE"
LEFT JOIN POMGR_SNP.SAMPLE_TRACKING
ON
  POMGR_SNP.SAMPLE_TRACKING.SAMPLE_ID = POMGR_SNP."SAMPLE".ID
RIGHT JOIN POMGR_SNP.LK_SAMPLE_LOCATION sample_location
ON
  POMGR_SNP.SAMPLE_TRACKING.LOCATION_ID = sample_location.ID
INNER JOIN POMGR_SNP.LK_SAMPLE_STATUS
ON
  POMGR_SNP.SAMPLE_TRACKING.STATUS_ID = POMGR_SNP.LK_SAMPLE_STATUS.ID
INNER JOIN POMGR_SNP.USERS
ON
  POMGR_SNP.SAMPLE_TRACKING.USER_ID = POMGR_SNP.USERS.ID
LEFT JOIN POMGR_SNP.SAMPLE_TRACKING_NUMBER
ON
  POMGR_SNP."SAMPLE".ID = POMGR_SNP.SAMPLE_TRACKING_NUMBER.SAMPLE_ID
INNER JOIN POMGR_SNP.TRACKING_NUMBER
ON
  POMGR_SNP.SAMPLE_TRACKING_NUMBER.TRACKING_NUMBER_ID =
  POMGR_SNP.TRACKING_NUMBER.ID
LEFT JOIN POMGR_SNP.SKU
ON
  POMGR_SNP."SAMPLE".SKU_ID = POMGR_SNP.SKU.ID
GROUP BY
  POMGR_SNP."SAMPLE".ID,
  POMGR_SNP."SAMPLE".PRODUCT_COLOR_ID,
  POMGR_SNP.SKU.SKU_CODE,
  POMGR_SNP.TRACKING_NUMBER.REF_NUMBER,
  to_date(POMGR_SNP.TRACKING_NUMBER.CREATE_DT, 'YYYY-MM-DD'),
  POMGR_SNP.USERS.USERNAME
ORDER BY
  POMGR_SNP."SAMPLE".ID DESC,
  POMGR_SNP.TRACKING_NUMBER.REF_NUMBER DESC,
  to_date(POMGR_SNP.TRACKING_NUMBER.CREATE_DT, 'YYYY-MM-DD') DESC