set echo off
set verify off
set termout on
set array 3000                      
-- set heading on
set headsep off
set pagesize 50000
set colsep "|"
set pages 50000
set feedback off
--set tab on
set trimspool on
-- recsep 
--set trimout on
set null "NULL"
set newpage none
set linesize 5000
spool /mnt/Post_Ready/zProd_Server/imageServer7/tmp/limbo/spool_IndiaBags.csv
SELECT
    POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE             AS Style_Number,
    POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL2_NAME            AS Gender,
    POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL4_NAME            AS Product_Type,
    POMGR_SNP.PRODUCT_SNAPSHOT.BRAND                  AS Brand_Name,
    POMGR_SNP.PRODUCT_SNAPSHOT.BULLET_7               AS Measure_Body,
    POMGR_SNP.PRODUCT_SNAPSHOT.BULLET_4               AS Measure_Drop,
    POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_COMPLETE_DT AS Prod_Complete_Date,
    POMGR_SNP.PRODUCT_SNAPSHOT.COPY_READY             AS Copy_Ready_Date,
    POMGR_SNP.PRODUCT_SNAPSHOT.IMAGE_READY            AS Image_Ready_Date,
    POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_STATUS      AS Production_Status,
    AVG(POMGR_SNP.PRODUCT_SNAPSHOT.SELLING_PRICE)     AS Selling_Price,
    SUM(POMGR_SNP.PRODUCT_SNAPSHOT.AVAILABLE_ON_HAND) AS Total_QTY,
    SUM(POMGR_SNP.PRODUCT_SNAPSHOT.AVAILABLE_ON_HAND * POMGR_SNP.PRODUCT_SNAPSHOT.SELLING_PRICE) AS Total_Value
FROM
    POMGR_SNP.PRODUCT_SNAPSHOT
WHERE
    POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_COMPLETE_DT >= TRUNC((SysDate) - 365)
AND 
    POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL4_NAME  = 'handbags'
OR
    POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL4_NAME  = 'bags'
GROUP BY
    POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE,
    POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL2_NAME,
    POMGR_SNP.PRODUCT_SNAPSHOT.BRAND,
    POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_COMPLETE_DT,
    POMGR_SNP.PRODUCT_SNAPSHOT.COPY_READY,
    POMGR_SNP.PRODUCT_SNAPSHOT.IMAGE_READY,
    POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL4_NAME,
    POMGR_SNP.PRODUCT_SNAPSHOT.BULLET_7,
    POMGR_SNP.PRODUCT_SNAPSHOT.BULLET_4,
    POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_STATUS
HAVING
    SUM(POMGR_SNP.PRODUCT_SNAPSHOT.AVAILABLE_ON_HAND) >= 1
ORDER BY
    SUM(POMGR_SNP.PRODUCT_SNAPSHOT.AVAILABLE_ON_HAND * POMGR_SNP.PRODUCT_SNAPSHOT.SELLING_PRICE) DESC,
    POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL2_NAME DESC,
    POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE DESC;
spool off;
exit;
