SELECT DISTINCT
  POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE                                AS "colorstyle",
  POMGR_SNP.SKU.SKU_CODE                                               AS "sku",
  POMGR_SNP.PRODUCT_SNAPSHOT.VENDOR_SIZE_CHART                         AS "Vendor_Size_Chart",
  POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_STATUS                         AS "IPTC:CopyrightNotice",
  POMGR_SNP.PRODUCT_SNAPSHOT.PO_HDR                                    AS "IPTC:PONumber",
  POMGR_SNP.USERS.USERNAME                                             AS "IPTC:MerchantName",
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS                             AS "IPTC:Source",
  to_date(POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS_DATE, 'YYYY-MM-DD') AS
  "IPTC:SampleStatusDate",
  SUM(POMGR_SNP.PRODUCT_SNAPSHOT.AVAILABLE_ON_HAND)                        AS "IPTC:SampleInventory",
  to_date(POMGR_SNP.PRODUCT_SNAPSHOT.COPY_READY, 'YYYY-MM-DD')             AS COPY_READY,
  to_date(POMGR_SNP.PRODUCT_SNAPSHOT.IMAGE_READY, 'YYYY-MM-DD')            AS IMAGE_READY,
  to_date(POMGR_SNP.PRODUCT_SNAPSHOT.START_DATE, 'YYYY-MM-DD')             AS START_DATE,
  to_date(POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_COMPLETE_DT, 'YYYY-MM-DD') AS
  PRODUCTION_COMPLETE_DT,
  to_date(POMGR_SNP.PRODUCT_SNAPSHOT.ORIGINAL_START_DATE, 'YYYY-MM-DD') AS
  ORIGINAL_START_DATE,
  POMGR_SNP.PRODUCT_SNAPSHOT.COLOR_GROUP AS "Color",
  POMGR_SNP."SAMPLE".STATUS_ID           AS "StatusSample_ID",
  POMGR_SNP."SAMPLE".PO_SKU_ID           AS POSKU_ID,
  POMGR_SNP."SAMPLE".SKU_ID              AS SKU_ID,
  POMGR_SNP.SKU.VENDOR_SIZE_VALUE_ID     AS "Vendor_Size_ID",
  POMGR_SNP."SAMPLE".ID                  AS "SampleID",
  POMGR_SNP.TRACKING_NUMBER.REF_NUMBER                          AS "UPS_TrackingID",
  POMGR_SNP.TRACKING_NUMBER.CARRIER_ID                          AS "CarrierID",
  to_date(POMGR_SNP.TRACKING_NUMBER.CREATE_DT, 'YYYY-MM-DD')    AS "Tracking_Date"
FROM
  POMGR_SNP.PRODUCT_SNAPSHOT
LEFT JOIN ATG_SNP.EVENT_PRODUCT_COLOR Event_ID_StyleNumber
ON
  POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE = Event_ID_StyleNumber.PRODUCT_COLOR_ID
LEFT JOIN ATG_SNP.EVENT_GROUP
ON
  ATG_SNP.EVENT_GROUP.ID = Event_ID_StyleNumber.EVENT_ID
INNER JOIN POMGR_SNP.PO_HDR
ON
  POMGR_SNP.PRODUCT_SNAPSHOT.PO_HDR = POMGR_SNP.PO_HDR.ID
INNER JOIN POMGR_SNP.USERS
ON
  POMGR_SNP.USERS.ID = POMGR_SNP.PO_HDR.USER_ID
INNER JOIN POMGR_SNP.SKU
ON
  POMGR_SNP.PRODUCT_SNAPSHOT.SKU = POMGR_SNP.SKU.SKU_CODE
INNER JOIN POMGR_SNP."SAMPLE"
ON
  POMGR_SNP.SKU.ID = POMGR_SNP."SAMPLE".SKU_ID
INNER JOIN POMGR_SNP.SAMPLE_TRACKING_NUMBER
ON
  POMGR_SNP."SAMPLE".ID = POMGR_SNP.SAMPLE_TRACKING_NUMBER.SAMPLE_ID
INNER JOIN POMGR_SNP.TRACKING_NUMBER
ON
  POMGR_SNP.SAMPLE_TRACKING_NUMBER.TRACKING_NUMBER_ID =
  POMGR_SNP.TRACKING_NUMBER.ID
WHERE
  (
    POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS_DATE >= TRUNC((SysDate) - 30)
  AND POMGR_SNP.PRODUCT_SNAPSHOT.INACTIVE_REASON  IS NULL
  AND POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS     = 'Scanned In at Bluefly'
  )
OR
  (
    POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS_DATE >= TRUNC((SysDate) - 30)
  AND POMGR_SNP.PRODUCT_SNAPSHOT.INACTIVE_REASON  IS NULL
  AND POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS     = 'Sample Sent to Bluefly'
  )
OR
  (
    POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS = 'Scanned Out to Buyers'
  )
GROUP BY
  POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE,
  POMGR_SNP.SKU.SKU_CODE,
  POMGR_SNP.PRODUCT_SNAPSHOT.VENDOR_SIZE_CHART,
  POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_STATUS,
  POMGR_SNP.PRODUCT_SNAPSHOT.PO_HDR,
  POMGR_SNP.USERS.USERNAME,
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS,
  POMGR_SNP.PRODUCT_SNAPSHOT.COLOR_GROUP,
  POMGR_SNP."SAMPLE".STATUS_ID,
  POMGR_SNP."SAMPLE".PO_SKU_ID,
  POMGR_SNP."SAMPLE".SKU_ID,
  POMGR_SNP.SKU.VENDOR_SIZE_VALUE_ID,
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS_DATE,
  POMGR_SNP.PRODUCT_SNAPSHOT.COPY_READY,
  POMGR_SNP.PRODUCT_SNAPSHOT.IMAGE_READY,
  POMGR_SNP.PRODUCT_SNAPSHOT.START_DATE,
  POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_COMPLETE_DT,
  POMGR_SNP.PRODUCT_SNAPSHOT.ORIGINAL_START_DATE,
  POMGR_SNP."SAMPLE".ID,
  POMGR_SNP.TRACKING_NUMBER.REF_NUMBER,
  POMGR_SNP.TRACKING_NUMBER.CARRIER_ID,
  POMGR_SNP.TRACKING_NUMBER.CREATE_DT
HAVING
  SUM(POMGR_SNP.PRODUCT_SNAPSHOT.AVAILABLE_ON_HAND) >= 0
ORDER BY
  POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE DESC Nulls Last,
  to_date(POMGR_SNP.TRACKING_NUMBER.CREATE_DT, 'YYYY-MM-DD') DESC Nulls Last
