#!/usr/bin/env python
def query_vendors_styles(vendorname):
    import sqlalchemy
    orcl_engine = sqlalchemy.create_engine('oracle+cx_oracle://prod_team_ro:9thfl00r@borac101-vip.l3.bluefly.com:1521/bfyprd11')    
    connection = orcl_engine.connect()
    ## POMGR.INVENTORY.TOTAL_WH_RCVD_QTY,
    ## POMGR.INVENTORY.SOLD,
    ## POMGR.INVENTORY.AVAL_ON_HAND,
    # querymake_vendor_po_DSSPRD1 = "SELECT POMGR_SNP.PRODUCT_COLOR.ID AS colorstyle, POMGR_SNP.PRODUCT_COLOR.VENDOR_STYLE AS vendor_style, POMGR_SNP.PO_LINE.PO_HDR_ID AS po_hdr_id FROM POMGR_SNP.PRODUCT_COLOR INNER JOIN POMGR_SNP.PO_LINE ON POMGR_SNP.PRODUCT_COLOR.ID = POMGR_SNP.PO_LINE.PRODUCT_COLOR_ID WHERE POMGR_SNP.PRODUCT_COLOR.VENDOR_STYLE LIKE '" + vnum + "%' AND POMGR_SNP.PO_LINE.PO_HDR_ID = '" + ponum + "'"
    # querymake_vendors_styles = "SELECT DISTINCT POMGR.PO_LINE.PRODUCT_COLOR_ID as colorstyle, POMGR.PO_LINE.PO_HDR_ID as po_hdr_id, POMGR.VENDOR.NAME AS vendor_name, POMGR.PRODUCT_COLOR.COPY_READY_DT as copy_ready_dt, POMGR.PRODUCT_COLOR.IMAGE_READY_DT as image_ready_dt, POMGR.PRODUCT_COLOR.PRODUCTION_COMPLETE_DT, POMGR.PRODUCT_COLOR.ACTIVE, POMGR.VENDOR.THIRD_SUPPLIER_ID, POMGR.LK_PO_TYPE.NAME AS po_type, POMGR.PRODUCT_COLOR.CREATED_DATE as create_dt, POMGR.PRODUCT_COLOR.MODIFIED_DATE as modify_dt, POMGR.PRODUCT_DETAIL.MATERIAL as material, POMGR.PRODUCT_DETAIL.LONG_DESCRIPTION as description, POMGR.PRODUCT_COLOR.VERSION as version FROM POMGR.PRODUCT_COLOR RIGHT JOIN POMGR.PO_LINE ON POMGR.PO_LINE.PRODUCT_COLOR_ID = POMGR.PRODUCT_COLOR.ID RIGHT JOIN POMGR.PO_HDR ON POMGR.PO_HDR.ID = POMGR.PO_LINE.PO_HDR_ID RIGHT JOIN POMGR.VENDOR ON POMGR.VENDOR.ID = POMGR.PO_HDR.VENDOR_ID INNER JOIN POMGR.LK_PO_TYPE ON POMGR.LK_PO_TYPE.ID = POMGR.PO_HDR.PO_TYPE_ID LEFT JOIN POMGR.INVENTORY ON POMGR.INVENTORY.PRODUCT_COLOR_ID = POMGR.PRODUCT_COLOR.ID LEFT JOIN POMGR.PRODUCT_DETAIL ON POMGR.PRODUCT_COLOR.PRODUCT_ID = POMGR.PRODUCT_DETAIL.PRODUCT_ID WHERE POMGR.VENDOR.NAME LIKE '%{0}%' ORDER BY POMGR.PO_LINE.PRODUCT_COLOR_ID DESC Nulls Last, POMGR.PRODUCT_COLOR.IMAGE_READY_DT DESC Nulls Last".format(vendorname)
    querymake_vendors_product_details = "SELECT DISTINCT POMGR.PO_LINE.PRODUCT_COLOR_ID as colorstyle, POMGR.PO_LINE.PO_HDR_ID as po_hdr_id, POMGR.VENDOR.NAME AS vendor_name, POMGR.PRODUCT_COLOR.COPY_READY_DT as copy_ready_dt, POMGR.PRODUCT_COLOR.IMAGE_READY_DT as image_ready_dt, POMGR.PRODUCT_COLOR.PRODUCTION_COMPLETE_DT, POMGR.PRODUCT_COLOR.ACTIVE, POMGR.VENDOR.THIRD_SUPPLIER_ID, POMGR.LK_PO_TYPE.NAME AS po_type, POMGR.PRODUCT_COLOR.CREATED_DATE as create_dt, POMGR.PRODUCT_COLOR.MODIFIED_DATE as modify_dt, POMGR.PRODUCT_DETAIL.MATERIAL as material, POMGR.PRODUCT_COLOR_DETAIL.SHORT_NAME as short_name, POMGR.PRODUCT_DETAIL.LONG_DESCRIPTION as description, POMGR.PRODUCT_COLOR_DETAIL.BULLET_1 as bullet1, POMGR.PRODUCT_COLOR_DETAIL.BULLET_2 as bullet2, POMGR.PRODUCT_COLOR_DETAIL.BULLET_3 as bullet3, POMGR.PRODUCT_COLOR_DETAIL.BULLET_4 as bullet4, POMGR.PRODUCT_COLOR_DETAIL.BULLET_5 as bullet5, POMGR.PRODUCT_COLOR_DETAIL.BULLET_6 as bullet6, POMGR.PRODUCT_COLOR_DETAIL.BULLET_7 as bullet7, POMGR.PRODUCT_COLOR_DETAIL.BULLET_8 as bullet8, POMGR.PRODUCT_COLOR_DETAIL.BULLET_9 as bullet9, POMGR.PRODUCT_COLOR.VERSION as version FROM POMGR.PRODUCT_COLOR RIGHT JOIN POMGR.PO_LINE ON POMGR.PO_LINE.PRODUCT_COLOR_ID = POMGR.PRODUCT_COLOR.ID RIGHT JOIN POMGR.PO_HDR ON POMGR.PO_HDR.ID = POMGR.PO_LINE.PO_HDR_ID RIGHT JOIN POMGR.VENDOR ON POMGR.VENDOR.ID = POMGR.PO_HDR.VENDOR_ID INNER JOIN POMGR.LK_PO_TYPE ON POMGR.LK_PO_TYPE.ID = POMGR.PO_HDR.PO_TYPE_ID LEFT JOIN POMGR.INVENTORY ON POMGR.INVENTORY.PRODUCT_COLOR_ID = POMGR.PRODUCT_COLOR.ID LEFT JOIN POMGR.PRODUCT_DETAIL ON POMGR.PRODUCT_COLOR.PRODUCT_ID = POMGR.PRODUCT_DETAIL.PRODUCT_ID LEFT JOIN POMGR.PRODUCT_COLOR_DETAIL ON POMGR.PRODUCT_COLOR.PRODUCT_ID = POMGR.PRODUCT_COLOR_DETAIL.PRODUCT_COLOR_ID WHERE POMGR.VENDOR.NAME LIKE '%{0}%' ORDER BY POMGR.PO_LINE.PRODUCT_COLOR_ID DESC Nulls Last, POMGR.PRODUCT_COLOR.IMAGE_READY_DT DESC Nulls Last".format(vendorname)
    #querymake_vendors_productimage_details = "SELECT DISTINCT POMGR.PO_LINE.PRODUCT_COLOR_ID as colorstyle, POMGR.PO_LINE.PO_HDR_ID as po_hdr_id, POMGR.VENDOR.NAME AS vendor_name, POMGR.PRODUCT_COLOR.COPY_READY_DT as copy_ready_dt, POMGR.PRODUCT_COLOR.IMAGE_READY_DT as image_ready_dt, POMGR.PRODUCT_COLOR.PRODUCTION_COMPLETE_DT, POMGR.PRODUCT_COLOR.ACTIVE, POMGR.VENDOR.THIRD_SUPPLIER_ID, POMGR.LK_PO_TYPE.NAME AS po_type, POMGR.PRODUCT_COLOR.CREATED_DATE as create_dt, POMGR.PRODUCT_COLOR.MODIFIED_DATE as modify_dt, POMGR.PRODUCT_DETAIL.MATERIAL as material, POMGR.PRODUCT_COLOR_DETAIL.SHORT_NAME as short_name, POMGR.PRODUCT_DETAIL.LONG_DESCRIPTION as description, POMGR.PRODUCT_COLOR_DETAIL.ALTERNATE_IMAGE_1 as alt1, POMGR.PRODUCT_COLOR_DETAIL.ALTERNATE_IMAGE_2 as alt2, POMGR.PRODUCT_COLOR_DETAIL.ALTERNATE_IMAGE_3 as alt3, POMGR.PRODUCT_COLOR_DETAIL.ALTERNATE_IMAGE_4 as alt4, POMGR.PRODUCT_COLOR_DETAIL.ALTERNATE_IMAGE_5 as alt5, POMGR.PRODUCT_COLOR.VERSION as version FROM POMGR.PRODUCT_COLOR RIGHT JOIN POMGR.PO_LINE ON POMGR.PO_LINE.PRODUCT_COLOR_ID = POMGR.PRODUCT_COLOR.ID RIGHT JOIN POMGR.PO_HDR ON POMGR.PO_HDR.ID = POMGR.PO_LINE.PO_HDR_ID RIGHT JOIN POMGR.VENDOR ON POMGR.VENDOR.ID = POMGR.PO_HDR.VENDOR_ID INNER JOIN POMGR.LK_PO_TYPE ON POMGR.LK_PO_TYPE.ID = POMGR.PO_HDR.PO_TYPE_ID LEFT JOIN POMGR.INVENTORY ON POMGR.INVENTORY.PRODUCT_COLOR_ID = POMGR.PRODUCT_COLOR.ID LEFT JOIN POMGR.PRODUCT_DETAIL ON POMGR.PRODUCT_COLOR.PRODUCT_ID = POMGR.PRODUCT_DETAIL.PRODUCT_ID LEFT JOIN POMGR.PRODUCT_COLOR_DETAIL ON POMGR.PRODUCT_COLOR.PRODUCT_ID = POMGR.PRODUCT_COLOR_DETAIL.PRODUCT_COLOR_ID WHERE POMGR.VENDOR.NAME LIKE '%{0}%' ORDER BY POMGR.PO_LINE.PRODUCT_COLOR_ID DESC Nulls Last, POMGR.PRODUCT_COLOR.IMAGE_READY_DT DESC Nulls Last".format(vendorname)

    result = connection.execute(querymake_vendors_product_details)
    styles = {}
    for row in result:
        style = {}
        style['vendor_name'] = row['vendor_name']
        style['short_name'] = row['short_name']
        style['version'] = row['version']

        styles[row['colorstyle']] = style
        
    #print consigstyles
    connection.close()
    return styles
    


import sys
if __name__ == '__main__':
    try:
        vendorname = sys.argv[1]
        query_vendors_styles(vendorname)
    except:
        print "This Failed"
        pass
