
SET TRIMOUT ON
SET FEEDBACK OFF
--SET TAB ON
SET PAGESIZE 0
SET SERVEROUTPUT OFF
SET HEADING OFF
SET NEWPAGE 0
SET ECHO OFF
SET VERIFY OFF
SET WRAP OFF

WITH data AS ( SELECT DISTINCT POMGR.SUPPLIER_INGEST_STYLE.BLUEFLY_PRODUCT_COLOR AS colorstyle,
POMGR.SUPPLIER_INGEST_IMAGE.IMAGE_NUMBER AS alt,
CASE
    WHEN to_date(POMGR.SUPPLIER_INGEST_IMAGE.CREATED_DATE) > to_date(POMGR.SUPPLIER_INGEST_STYLE.CREATED_DATE)
    THEN to_date(POMGR.SUPPLIER_INGEST_IMAGE.CREATED_DATE) - to_date(POMGR.SUPPLIER_INGEST_STYLE.CREATED_DATE)
    ELSE to_date(POMGR.SUPPLIER_INGEST_STYLE.CREATED_DATE) - to_date(POMGR.SUPPLIER_INGEST_IMAGE.CREATED_DATE)
END imgstyle_amt,
CASE
    WHEN to_date(POMGR.SUPPLIER_INGEST_IMAGE.CREATED_DATE) > to_date(POMGR.PRODUCT_COLOR.IMAGE_READY_DT)
    THEN 'Update'
    ELSE 'NoChange'
END req_action,
CASE
    WHEN
        (
        to_date(POMGR.SUPPLIER_INGEST_IMAGE.CREATED_DATE) > to_date(POMGR.PRODUCT_COLOR.IMAGE_READY_DT)
        AND POMGR.SUPPLIER_INGEST_STYLE.VENDOR_ID NOT LIKE '%Skye%'
        OR POMGR.SUPPLIER_INGEST_STYLE.VENDOR_ID NOT LIKE '%SWI%'
        )
    THEN 'Y'
    ELSE 'N'
END record_mod,
POMGR.PO_LINE.PO_HDR_ID                      AS po_number,
POMGR.SUPPLIER_INGEST_STYLE.VENDOR_ID        AS vendor_name,
POMGR.SUPPLIER_INGEST_IMAGE.CREATED_DATE     AS image_dt,
POMGR.SUPPLIER_INGEST_STYLE.CREATED_DATE     AS style_dt,
POMGR.SUPPLIER_INGEST_STYLE.MODIFIED_DATE    AS style_mod_dt,
POMGR.PRODUCT_COLOR.IMAGE_READY_DT           AS image_ready_dt,
POMGR.PRODUCT_COLOR.PRODUCTION_COMPLETE_DT   AS production_complete_dt,
POMGR.PRODUCT_COLOR.COPY_READY_DT            AS copy_ready_dt,
POMGR.SUPPLIER_INGEST_SKU.CREATED_DATE       AS skuecreate,
POMGR.SUPPLIER_INGEST_SKU.MODIFIED_DATE      AS skumod,
POMGR.SUPPLIER_INGEST_IMAGE.URL              AS image_url,
POMGR.SUPPLIER_INGEST_STYLE.VENDOR_BRAND     AS vendor_brand,
POMGR.SUPPLIER_INGEST_SKU.THIRD_SUPPLIER_ID  AS third_supplierid,
POMGR.SUPPLIER_INGEST_STYLE.VENDOR_STYLE     AS vendor_style,
POMGR.SUPPLIER_INGEST_IMAGE.STYLE_ID         AS genstyleid,
POMGR.SUPPLIER_INGEST_STYLE.BLUEFLY_CATEGORY AS product_folder
FROM
POMGR.SUPPLIER_INGEST_STYLE
LEFT JOIN POMGR.SUPPLIER_INGEST_SKU
ON
POMGR.SUPPLIER_INGEST_SKU.STYLE_ID = POMGR.SUPPLIER_INGEST_STYLE.ID
LEFT JOIN POMGR.SUPPLIER_INGEST_IMAGE
ON
POMGR.SUPPLIER_INGEST_STYLE.ID = POMGR.SUPPLIER_INGEST_IMAGE.STYLE_ID
LEFT JOIN POMGR.PO_LINE
ON
POMGR.PO_LINE.PRODUCT_COLOR_ID = POMGR.SUPPLIER_INGEST_STYLE.BLUEFLY_PRODUCT_COLOR
LEFT JOIN POMGR.PRODUCT_COLOR
ON
POMGR.PRODUCT_COLOR.ID = POMGR.PO_LINE.PRODUCT_COLOR_ID
WHERE
POMGR.SUPPLIER_INGEST_IMAGE.URL IS NOT NULL
AND POMGR.SUPPLIER_INGEST_IMAGE.CREATED_DATE >= SysDate - 10
AND POMGR.SUPPLIER_INGEST_IMAGE.IMAGE_NUMBER <= 6
AND POMGR.SUPPLIER_INGEST_STYLE.VENDOR_ID not LIKE '%Vault%'
AND POMGR.SUPPLIER_INGEST_STYLE.VENDOR_ID not LIKE '%Skye%'
AND POMGR.SUPPLIER_INGEST_STYLE.VENDOR_ID not LIKE '%SWI%'
AND POMGR.PRODUCT_COLOR.IMAGE_READY_DT       <= SysDate - 2 )
SELECT data.colorstyle FROM data WHERE (data.imgstyle_amt < 10 AND data.imgstyle_amt > 1 AND data.req_action is NOT NULL);

exit;
