set echo off
set verify off
set termout on
set array 4000    
set wrap off
--set heading on
--set headsep "|"
set pagesize 50000
set colsep ","
set pages 50000
set feedback off
--set tab on
set trimspool on
--set recsep "|"
--set trimout on
set null "-"
set newpage none
set linesize 32766
spool /mnt/Post_Ready/zProd_Server/imageServer7/tmp/limbo/spoolpmaimportprodsnapshotlive.csv


SELECT DISTINCT
  MAX(DISTINCT POMGR_SNP.SKU.PRODUCT_COLOR_ID)                          AS "colorstyle",
  POMGR_SNP.BRAND.NAME                                                  AS "brand",
  POMGR_SNP.LK_PRODUCT_STATUS.NAME                                      AS "production_status",
  POMGR_SNP.PO_LINE.PO_HDR_ID                                           AS "po_number",
  POMGR_SNP.LK_SAMPLE_STATUS.NAME                                       AS "sample_status",
  MAX(to_date(POMGR_SNP.SAMPLE_TRACKING.CREATE_DT, 'YYYY-MM-DD'))       AS "status_dt",
  to_date(POMGR_SNP.PRODUCT_COLOR.COPY_READY_DT, 'YYYY-MM-DD')          AS "copy_ready_dt",
  to_date(POMGR_SNP.PRODUCT_COLOR.IMAGE_READY_DT, 'YYYY-MM-DD')         AS "image_ready_dt",
  to_date(POMGR_SNP.PRODUCT_COLOR.PRODUCTION_COMPLETE_DT, 'YYYY-MM-DD') AS "production_complete_dt",
  to_date(POMGR_SNP.PRODUCT_COLOR.START_DATE, 'YYYY-MM-DD')             AS "start_dt",
  to_date(POMGR_SNP.PRODUCT_COLOR.ORIGINAL_START_DATE, 'YYYY-MM-DD')    AS "orig_start_dt",
  POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL2_NAME                                  AS "gender",
  POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL3_NAME                                  AS "category",
  POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL4_NAME                                  AS "product_type",
  to_date(POMGR_SNP.PRODUCT_COLOR_DETAIL.PHOTOGRAPHED_DATE, 'YYYY-MM-DD') AS "sample_image_dt",
  POMGR_SNP.PRODUCT_COLOR.VENDOR_STYLE                                    AS "vendor_style",
  POMGR_SNP.COLOR_GROUP.DESCRIPTION                                       AS "color",
  POMGR_SNP.PRODUCT_FOLDER_DENORMALIZED.LABEL                             AS "product_subtype",
  POMGR_SNP.SAMPLE_TRACKING_NUMBER.SAMPLE_ID                              AS "sample_id",
  MAX(POMGR_SNP.SKU.SKU_CODE)                                             AS "sku",
  MAX(POMGR_SNP.TRACKING_NUMBER.REF_NUMBER)                               AS "track_number",
  MAX(to_date(POMGR_SNP.TRACKING_NUMBER.CREATE_DT, 'YYYY-MM-DD'))         AS "track_dt",
  POMGR_SNP.LK_SAMPLE_LOCATION.NAME                                       AS "sample_location",
  ATG_SNP.USERS.USERNAME                                                  AS "track_user",
  ATG_SNP.LK_PO_TYPE.NAME                                                 AS "po_type"
FROM
  POMGR_SNP.PRODUCT_COLOR
LEFT JOIN POMGR_SNP.COLOR_GROUP
ON
  POMGR_SNP.PRODUCT_COLOR.COLOR_GROUP_ID = POMGR_SNP.COLOR_GROUP.ID
LEFT JOIN POMGR_SNP.LK_PRODUCT_STATUS
ON
  POMGR_SNP.PRODUCT_COLOR.PRODUCTION_STATUS_ID = POMGR_SNP.LK_PRODUCT_STATUS.ID
LEFT JOIN POMGR_SNP.PRODUCT_COLOR_DETAIL
ON
  POMGR_SNP.PRODUCT_COLOR.ID = POMGR_SNP.PRODUCT_COLOR_DETAIL.PRODUCT_COLOR_ID
LEFT JOIN POMGR_SNP.SKU
ON
  POMGR_SNP.PRODUCT_COLOR.ID = POMGR_SNP.SKU.PRODUCT_COLOR_ID
LEFT JOIN POMGR_SNP.PO_SKU
ON
  POMGR_SNP.SKU.ID = POMGR_SNP.PO_SKU.SKU_ID
LEFT JOIN POMGR_SNP."SAMPLE"
ON
  POMGR_SNP."SAMPLE".PO_SKU_ID = POMGR_SNP.PO_SKU.ID
LEFT JOIN POMGR_SNP.SAMPLE_TRACKING
ON
  POMGR_SNP."SAMPLE".ID = POMGR_SNP.SAMPLE_TRACKING.SAMPLE_ID
LEFT JOIN ATG_SNP.USERS
ON
  POMGR_SNP.SAMPLE_TRACKING.USER_ID = ATG_SNP.USERS.ID
LEFT JOIN POMGR_SNP.LK_SAMPLE_STATUS
ON
  POMGR_SNP.SAMPLE_TRACKING.STATUS_ID = POMGR_SNP.LK_SAMPLE_STATUS.ID
LEFT JOIN POMGR_SNP.SAMPLE_TRACKING_NUMBER
ON
  POMGR_SNP.SAMPLE_TRACKING.SAMPLE_ID =
  POMGR_SNP.SAMPLE_TRACKING_NUMBER.SAMPLE_ID
LEFT JOIN POMGR_SNP.TRACKING_NUMBER
ON
  POMGR_SNP.SAMPLE_TRACKING_NUMBER.TRACKING_NUMBER_ID =
  POMGR_SNP.TRACKING_NUMBER.ID
LEFT JOIN POMGR_SNP.LK_SAMPLE_LOCATION
ON
  POMGR_SNP.SAMPLE_TRACKING.LOCATION_ID = POMGR_SNP.LK_SAMPLE_LOCATION.ID
LEFT JOIN POMGR_SNP.PO_LINE
ON
  POMGR_SNP.PO_SKU.PO_LINE_ID = POMGR_SNP.PO_LINE.ID
LEFT JOIN POMGR_SNP.PO_HDR
ON
  POMGR_SNP.PO_LINE.PO_HDR_ID = POMGR_SNP.PO_HDR.ID
LEFT JOIN POMGR_SNP.LK_PO_STATUS
ON
  POMGR_SNP.PO_HDR.PO_STATUS_ID = POMGR_SNP.LK_PO_STATUS.ID
LEFT JOIN ATG_SNP.LK_PO_TYPE
ON
  POMGR_SNP.PO_HDR.PO_TYPE_ID = ATG_SNP.LK_PO_TYPE.ID
LEFT JOIN POMGR_SNP.PRODUCT
ON
  POMGR_SNP.PRODUCT_COLOR.PRODUCT_ID = POMGR_SNP.PRODUCT.ID
INNER JOIN POMGR_SNP.BRAND
ON
  POMGR_SNP.PRODUCT.BRAND_ID = POMGR_SNP.BRAND.ID
INNER JOIN POMGR_SNP.PRODUCT_FOLDER_DENORMALIZED
ON
  POMGR_SNP.PRODUCT.PRODUCT_FOLDER_ID =
  POMGR_SNP.PRODUCT_FOLDER_DENORMALIZED.ID
LEFT JOIN POMGR_SNP.PRODUCT_SNAPSHOT
ON
  POMGR_SNP.SKU.PRODUCT_COLOR_ID = POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE
WHERE
  POMGR_SNP.SAMPLE_TRACKING.CREATE_DT >= trunc(sysdate - 550) 
GROUP BY
  POMGR_SNP.BRAND.NAME,
  POMGR_SNP.LK_PRODUCT_STATUS.NAME,
  POMGR_SNP.PO_LINE.PO_HDR_ID,
  POMGR_SNP.LK_SAMPLE_STATUS.NAME,
  to_date(POMGR_SNP.PRODUCT_COLOR.COPY_READY_DT, 'YYYY-MM-DD'),
  to_date(POMGR_SNP.PRODUCT_COLOR.IMAGE_READY_DT, 'YYYY-MM-DD'),
  to_date(POMGR_SNP.PRODUCT_COLOR.PRODUCTION_COMPLETE_DT, 'YYYY-MM-DD'),
  to_date(POMGR_SNP.PRODUCT_COLOR.START_DATE, 'YYYY-MM-DD'),
  to_date(POMGR_SNP.PRODUCT_COLOR.ORIGINAL_START_DATE, 'YYYY-MM-DD'),
  POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL2_NAME,
  POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL3_NAME,
  POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL4_NAME,
  to_date(POMGR_SNP.PRODUCT_COLOR_DETAIL.PHOTOGRAPHED_DATE, 'YYYY-MM-DD'),
  POMGR_SNP.PRODUCT_COLOR.VENDOR_STYLE,
  POMGR_SNP.COLOR_GROUP.DESCRIPTION,
  POMGR_SNP.PRODUCT_FOLDER_DENORMALIZED.LABEL,
  POMGR_SNP.SAMPLE_TRACKING_NUMBER.SAMPLE_ID,
  ATG_SNP.USERS.USERNAME,
  ATG_SNP.LK_PO_TYPE.NAME,
  POMGR_SNP.LK_SAMPLE_LOCATION.NAME,
  POMGR_SNP.PRODUCT.BRAND_ID,
  POMGR_SNP.PRODUCT.PRODUCT_FOLDER_ID
ORDER BY
  MAX(DISTINCT POMGR_SNP.SKU.PRODUCT_COLOR_ID) DESC,
  MAX(to_date(POMGR_SNP.SAMPLE_TRACKING.CREATE_DT, 'YYYY-MM-DD')) DESC;
  
spool off
exit;
