set echo off
set verify off
set termout on
set array 3000                      
-- set heading on
set headsep off
set pagesize 50000
set colsep ","
set pages 50000
set feedback off
--set tab on
set trimspool on
-- recsep 
--set trimout on
set null "-"
set newpage none
set linesize 5000
-- spool /mnt/Post_Complete/CSV_updates/PrdExtra_Photoshop_Logs/spoolexiftoolCsvMetaData.csv
spool /mnt/Post_Ready/zProd_Server/imageServer7/tmp/limbo/spoolexiftoolCsvMetaData.csv

SELECT DISTINCT
  POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE        AS "SourceFile",
  POMGR_SNP.PRODUCT_SNAPSHOT.BRAND             AS "Keywords",
  ATG_SNP.EVENT_GROUP.NAME                     AS "XMP:Album",
--  POMGR_SNP.PRODUCT_SNAPSHOT.START_DATE        AS "IPTC:SpecialInstructions",
  POMGR_SNP.PRODUCT_SNAPSHOT.COPY_READY        AS "IPTC:SpecialInstructions",
  POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL4_NAME       AS "XMP:Genre",
  POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_STATUS AS "IPTC:CopyrightNotice",
  ATG_SNP.EVENT_GROUP.ID                       AS "IPTC:Credit",
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS     AS "IPTC:Source",
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS_DATE             AS "IPTC:SimilarityIndex"
FROM
  POMGR_SNP.PRODUCT_SNAPSHOT
LEFT JOIN ATG_SNP.EVENT_PRODUCT_COLOR Event_ID_StyleNumber
ON
  POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE = Event_ID_StyleNumber.PRODUCT_COLOR_ID
LEFT JOIN ATG_SNP.EVENT_GROUP
ON
  ATG_SNP.EVENT_GROUP.ID = Event_ID_StyleNumber.EVENT_ID
WHERE
  POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_STATUS = 'Production Incomplete'
  AND POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS != 'Pending Sample'
  AND POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS != 'Sample Sent to Bluefly'
  AND POMGR_SNP.PRODUCT_SNAPSHOT.INACTIVE_REASON IS NULL
OR
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS       = 'Scanned In at Bluefly'
OR
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS       = 'Production Sample Received'
OR
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS       = 'Sample In Progress'
GROUP BY
  POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE,
  POMGR_SNP.PRODUCT_SNAPSHOT.BRAND,
  ATG_SNP.EVENT_GROUP.NAME,
  ATG_SNP.EVENT_GROUP.ID,
  POMGR_SNP.PRODUCT_SNAPSHOT.COPY_READY,
  POMGR_SNP.PRODUCT_SNAPSHOT.LEVEL4_NAME,
  POMGR_SNP.PRODUCT_SNAPSHOT.PRODUCTION_STATUS,
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS,
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS_DATE
--HAVING
--  SUM(POMGR_SNP.PRODUCT_SNAPSHOT.TOTAL_ON_HAND) > 0
ORDER BY
  POMGR_SNP.PRODUCT_SNAPSHOT.SAMPLE_STATUS_DATE DESC Nulls Last,
  COUNT(DISTINCT POMGR_SNP.PRODUCT_SNAPSHOT.COLORSTYLE) DESC Nulls Last,
  MAX(DISTINCT ATG_SNP.EVENT_GROUP.ID) Nulls Last;
spool off
exit;
